try{
                mainThread.join();
            }
            catch(Exception e){
                System.out.println(e);
            }